config/routes.rb
Rails.application.routes.draw do
  resources :every_pays
 
  get '/paid' ,to: "every_pays#payment_success" #for success_payment
  post '/every_pay/payment' , to: "every_pays#payment" #for create or genrate payment links.
  root 'every_pays#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/every_pay.rb
class EveryPay < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/every_pays_controller.rb
class EveryPaysController < ApplicationController
  before_action :set_every_pay, only: %i[ show edit update destroy]
  skip_before_action :verify_authenticity_token, only: [:payment,:pay]
  before_action :set_every_data, only: %i[ payment payment_success]

  require "active_merchant_every_pay"

  # GET /every_pays or /every_pays.json
  def index
    @every_pays = EveryPay.all
    # puts request.protocol + request.host
  end

  #do Payment using every_payment_gateway.
  def payment_success
    gateway=set_every_data
    payment_response = gateway.result(payment_reference: params[:payment_reference])
    EveryPay.create status: payment_response.params['payment_state'] ,amount: payment_response.params['initial_amount'] , payment_reference: params[:payment_reference]
    respond_to do |format|
        format.html { redirect_to every_pays_path, notice: "Payment was successfully paid." }
    end
  end

  #Create payment request and link using every_payment
  def payment
      gateway = set_every_data
      response = gateway.authorize(params[:amount].to_i*100, order_reference: "order ##{(0...8).map { (65 + rand(26)).chr }.join}", email: params[:email_address], customer_ip: "127.0.0.1",
      billing_line1: params[:address],
      billing_postcode: params[:zip_code],
      billing_state: params[:state],
      billing_city: params[:city],
      billing_country: params[:country]
      )
      # Use this url to redirect user to merchant portal
      response.authorization
      # Read status
      data = gateway.result(payment_reference: response.payment_reference)
      redirect_to data.params['payment_link']
      # puts data.to_json
  end


  # GET /every_pays/1 or /every_pays/1.json
  def show
  end

  # GET /every_pays/new
  def new
    @every_pay = EveryPay.new
  end

  # GET /every_pays/1/edit
  def edit
  end

  # POST /every_pays or /every_pays.json
  def create
    @every_pay = EveryPay.new(every_pay_params)

    respond_to do |format|
      if @every_pay.save
        format.html { redirect_to @every_pay, notice: "Every pay was successfully created." }
        format.json { render :show, status: :created, location: @every_pay }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @every_pay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /every_pays/1 or /every_pays/1.json
  def update
    respond_to do |format|
      if @every_pay.update(every_pay_params)
        format.html { redirect_to @every_pay, notice: "Every pay was successfully updated." }
        format.json { render :show, status: :ok, location: @every_pay }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @every_pay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /every_pays/1 or /every_pays/1.json
  def destroy
    @every_pay.destroy
    respond_to do |format|
      format.html { redirect_to every_pays_url, notice: "Every pay was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_every_pay
      @every_pay = EveryPay.find(params[:id])
    end

    #set every_pay configuration
    def set_every_data
      @gateway = ActiveMerchant::Billing::EveryPayGateway.new(
        api_username: "22a8a6b1324144b0",
        api_secret: "8260872fe1b2b30d1753f3d360cf6e83",
        account_name: "EUR3D1",
        gateway_url: "https://igw-demo.every-pay.com/api/v4",
        customer_url: "https://0bd2-112-196-23-171.ngrok.io/paid"
      )
      @gateway
    end
    # Only allow a list of trusted parameters through.
    def every_pay_params
      params.require(:every_pay).permit(:status, :amount, :response)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/every_pays_helper.rb
module EveryPaysHelper
end

app/views/every_pays/_form.html.erb
<%= form_with(model: every_pay) do |form| %>
  <% if every_pay.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(every_pay.errors.count, "error") %> prohibited this every_pay from being saved:</h2>

      <ul>
        <% every_pay.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :response %>
    <%= form.text_field :response %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/every_pays/edit.html.erb
<h1>Editing Every Pay</h1>

<%= render 'form', every_pay: @every_pay %>

<%= link_to 'Show', @every_pay %> |
<%= link_to 'Back', every_pays_path %>

app/views/every_pays/index.html.erb
<p id="notice"><%= notice %></p>


<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<div class="container wrapper">
<h1>Every Pays</h1>

            <div class="row cart-body">

                <form class="form-horizontal" action="/every_pay/payment" method="post">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-md-push-6 col-sm-push-6">
                    
                    <!--REVIEW ORDER END-->
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-md-pull-6 col-sm-pull-6">
                    <!--SHIPPING METHOD-->
                    <div class="panel panel-info">
                        <div class="panel-heading">Address</div>
                        <div class="panel-body">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <h4>Shipping Address</h4>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12"><strong>Amount:</strong></div>
                                <div class="col-md-12"><input type="text" name="amount" class="form-control" value="" /></div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12"><strong>Email Address:</strong></div>
                                <div class="col-md-12"><input type="text" name="email_address" class="form-control" value="" /></div>
                            </div>
                            
                            <div class="form-group">
                                <div class="col-md-6 col-xs-12">
                                    <strong>First Name:</strong>
                                    <input type="text" name="first_name" class="form-control" value="" />
                                </div>
                                <div class="span1"></div>
                                <div class="col-md-6 col-xs-12">
                                    <strong>Last Name:</strong>
                                    <input type="text" name="last_name" class="form-control" value="" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12"><strong>Address:</strong></div>
                                <div class="col-md-12">
                                    <input type="text" name="address" class="form-control" value="" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12"><strong>City:</strong></div>
                                <div class="col-md-12">
                                    <input type="text" name="city" class="form-control" value="" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12"><strong>State:</strong></div>
                                <div class="col-md-12">
                                    <input type="text" name="state" class="form-control" value="" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12"><strong>Country:</strong></div>
                                <div class="col-md-12">
                                    <input type="text" class="form-control" name="country" value="" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12"><strong>Zip / Postal Code:</strong></div>
                                <div class="col-md-12">
                                    <input type="text" name="zip_code" class="form-control" value="" />
                                </div>
                            </div>
                            
                            
                        </div>
                    </div>
                    <div class="form-group">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <button type="submit" class="btn btn-primary btn-submit-fix">Place Order</button>
                </div>
            </div>
                </div>
                
                </form>
            </div>
            <div class="row cart-footer">
        
            </div>
    </div>

app/views/every_pays/new.html.erb
<h1>New Every Pay</h1>

<%= render 'form', every_pay: @every_pay %>

<%= link_to 'Back', every_pays_path %>

app/views/every_pays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @every_pay.status %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @every_pay.amount %>
</p>

<p>
  <strong>Response:</strong>
  <%= @every_pay.response %>
</p>

<%= link_to 'Edit', edit_every_pay_path(@every_pay) %> |
<%= link_to 'Back', every_pays_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EveryPayIntegrations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>